title: My page!
theme: minima
author: Shivani
email: shb381@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  Just a test for setting up

# social links
github_username:  ShivaniB-TU

show_excerpts: true # set to false to remove excerpts on the homepage
